### ISSUE TITLE
Doing command does nothing

### ISSUE THREAD

**Issue by SouthernPixel** [henkelmax/audio-player#11]
You closed the previous question before i could even reply. I tried doing this command but it does nothing. It doesnt say anything in chat or give me any option to do anything with a file. I watched the showcase video and i did what you did but it doesnt do anything at all after entering the command "/audioplayer upload"

**Comment by henkelmax** [comment]
You can still reply to closed issues.
If you need help, please visit the Simple Voice Chat Discord server.

**Comment by SouthernPixel** [comment]
Sorry didnt notice that but about the mod, how would they help with an issue with a command they dont even have control over? Im having issue with your mod not voice mod

**Comment by SouthernPixel** [comment]
oh ok. I didnt notice that either apparently :|
