### ISSUE TITLE
I am not able to add the plugin PLZ HELP

### ISSUE THREAD

**Issue by jle646YT** [henkelmax/audio-player#12]
I am not able to add the plugin it says "No Mods Found". Plz help
![Screenshot (28)](https://user-images.githubusercontent.com/110491023/182448282-f85ee56c-1f0b-4b51-88af-30ba397734a8.png)

**Comment by henkelmax** [comment]
This is not a plugin.

**Comment by jle646YT** [comment]
It still wont let me add the mod.
