### ISSUE TITLE
TPS drops proportionally to the audio file's size when loading custom discs into jukeboxes on 1.19.1

### ISSUE THREAD

**Issue by OJS05** [henkelmax/audio-player#14]
When loading a custom disc into a jukebox on Fabric 1.19.1, it causes a significant drop in TPS proportional to the audio file's size. A 35Mb mp3 file caused TPS to dip to as low as 3 for a few seconds, and then return back to where it was before.

To reproduce:
1. Install the mod onto a fabric server running 1.19.1
2. Create a custom disc via server files
3. Load disc either by hand or by dropper into a jukebox
4. Watch TPS drop substantially

Other mods:
- Lithium
- Carpet / Carpet Extra
- Simple Voice Chat

**Comment by henkelmax** [comment]
This has already been fixed in e4f2d9c078de505bfeb3dd0bad8c820b297fd80c
