### ISSUE TITLE
Bring new features to 1.18.2

### ISSUE THREAD

**Issue by are** [henkelmax/audio-player#15]
**Is your feature request related to a problem? Please describe.**
Hi! Love the mod, however my server is stuck on 1.18.2 for some time. This mod's version on 1.18.2 is missing some of the features (and filebin isn't usable right now).

**Describe the solution you'd like**
Would it be possible to bring the new features to 1.18.2?

**Describe alternatives you've considered**
I am familiar with Java environment (although I don't have a modding setup), so if its possible to build it for 1.18.2 on my own, could you give me some pointers?

**Comment by henkelmax** [comment]
Won't happen, sorry. When you have about 40 mods that need porting to other Minecraft versions, I wouldn't have time for anything else.
