### ISSUE TITLE
Forge Port

### ISSUE THREAD

**Issue by OfficialPixelBrush** [henkelmax/audio-player#16]
**Is your feature request related to a problem? Please describe.**
I'm frustrated that there is no equivalent or similar mod to this one for Forge.

**Describe the solution you'd like**
A Port to Forge of this Mod, either by you or someone else.

**Describe alternatives you've considered**
There are no real alternatives, as nobody's made a comparable mod that works in a similar fashion

**Additional context**
You'll likely ignore this, but I just felt like telling you that there *is* demand for a Forge port of this.

**Comment by henkelmax** [comment]
I won't create a forge port, but I'm fine with people creating their own mod like this for forge.
