### ISSUE TITLE
New Update breaks some mp3s

### ISSUE THREAD

**Issue by FixingGlobe** [henkelmax/audio-player#18]
Latest update breaks previously compatible mp3s
(Copied AudioPlayerCommands.class from 1.4.3 over to 1.4.1 to get the new clear command)

**Steps to reproduce the issue**
Certain mp3s give out errors in the console and skip to a later part when inserting.
Can send some "privately"
They are compatible in 1.4.1 with latest api and voicechat.
Structure changed a lot in version 1.4.3 so the issue could be with simple voice chat.

**Log files**
06.09 16:28:20 [Server] INFO hip: Can't rewind stream by 528 bits!
06.09 16:28:20 [Server] INFO big_values too large! 485
06.09 16:28:20 [Server] INFO Blocktype == 0 and window-switching == 1 not allowed.
06.09 16:28:20 [Server] INFO hip: bitstream problem, resyncing skipping 42369 bytes...
06.09 16:28:20 [Server] INFO big_values too large! 488
06.09 16:28:20 [Server] INFO big_values too large! 302
06.09 16:28:20 [Server] INFO hip: Can't rewind stream by 1838 bits!
06.09 16:28:20 [Server] INFO hip: bitstream problem, resyncing skipping 92 bytes...
06.09 16:28:22 [Server] AudioPlayerThread/ Failed to load native Opus codec: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /?/.cache/JNA/temp/jna12765296003541176421.tmp)
06.09 16:28:22 [Server] AudioPlayerThread/ Failed to load native Opus codec - Falling back to Java Opus implementation

This is from one track, another throws hundreds of similar errors. I don't think Opus error is a problem since it was already present in 1.4.1.
Certain tracks are fine btw. The affected tracks have an image attached and are from various places so it's possible that they are a bit off-spec. 

**Versions**
- MC 1.1.9.2
- Quilt Loader 0.17.4 + qfapi 4 beta 11 + qsl beta 15 fabric 0.60.0
- audioplayer 1.19.2
- voicechat 2.3.9 fabric XOR quilt

**Comment by henkelmax** [comment]
Please send me your mp3 file. Please also check if this happens with Fabric (Not quilt). I also need the full logs.
What OS and CPU architecture are you using?

**Comment by FixingGlobe** [comment]
I'm not sure what my server hardware really is it's a Ryzen 5700X with shared threads and I'm moving hosting company in about a week so I don't know what OS they are using.
In the upcoming days I can try some configurations on my own computers.
Also here the link to the mp3s, wetransfer seemed like an easy option, expires in a few days.

https://we.tl/t-4Cxf9jHJVH

**Comment by FixingGlobe** [comment]
First log I've posted is from the Hogan file

**Comment by henkelmax** [comment]
![image](https://user-images.githubusercontent.com/13237524/188699404-e142e2c1-733e-4d03-bd72-059eafcc0d88.png)

The first mp3 seems to contain a video. Please try to put that file in Audacity and export it as an mp3.

> Please send me your mp3 file. Please also check if this happens with Fabric (Not quilt). I also need the full logs.
What OS and CPU architecture are you using?

You also didn't provide logs and if you've tried it with Fabric.

**Comment by FixingGlobe** [comment]
So I've tested it on a fabric server and same issue with these unclean mp3s. 
Fabric server ONLY had fabric api, voice chat and audioplayer.

I did a quick cleaning as wav with davinci resolve and the audio plays nicely, it even loads immediately even though the file is about 50 Megabytes. I did increase the size limit.
Will post a complete server log where I play the unclean Hogan soon.

We just downloaded some mp3s from questionable sites and uploaded them, like how a lot of users would.

**Comment by henkelmax** [comment]
Alright, if it works with converted audio files, its fine. Mp3 support is pretty limited anyways.

**Comment by FixingGlobe** [comment]
This explains a lot, I've had some other questionable mp3s that didn't load properly, so wav or cleaned mp3s are the future,
I'll stay on 1.4.1 with the new commands file until we converted everything...
Thanks for the help and also thanks for adding the clear nbt option, which only targets those with the musicplayer nbt :)
