### ISSUE TITLE
Error Creating mp3 Decoder

### ISSUE THREAD

**Issue by isaiahcweener** [henkelmax/audio-player#20]
**Bug description**
The copied server file sound does not play on music disc or goat horn.

**Steps to reproduce the issue**
1. Place "filename" in folder audioplayer_uploads
2. Enter Command /audioplayer serverfile "filename" and "Successfully Copied Sound. [Copy ID] [Put on music disc] [Put on goat horn]" should show up in chat
3. Have a music disc in hand and enter chat, then click on [Put on music disc]. "Successfully updated Music Disc" should show up in chat.
4. Place the music disc with the copied sound into a jukebox.
5. Error "Failed to play audio: Error creating mp3 decoder" shows when placing the music disc into the jukebox.

**Expected behavior**
When placing the music disc with the copied sound file into a jukebox the sound should play.

**Log files**
[21:22:38] [AudioPlayerThread/ERROR]: Failed to load LAME decoder: /lib64/libm.so.6: version `GLIBC_2.27' not found (required by /home/minecraft/multicraft/servers/server1556742/default/.cache/JNA/temp/jna1758424710131971888.tmp)
[21:22:38] [AudioPlayerThread/ERROR]: Failed to play audio: Error creating mp3 decoder
[21:22:52] [AudioPlayerThread/ERROR]: Failed to load LAME decoder: Could not initialize class de.maxhenkel.voicechat.lame4j.Lame

**Versions**
- Minecraft version: 1.19.2
- Fabric loader version: 0.14.9
- Mod version: 1.4.3

**Other mods**
[Server Side]
AudioPlayer Version: 1.4.3
Cloth Config Version: 8.2.88
Fabric API Version: 0.61.0
FerriteCore Version: 5.0.0
Lithium Version: 0.8.3
NoChatReports Version: 1.11.2
QuickHomes Version: 1.3.0
QuickSpawns Version: 1.0.3
QuickTeleports: 1.2.0
Status Version: 1.0.0
View Distance Fix Version: 1.0.0
Simple Voice Chat 2.3.9
**Note: The problem persists even when all mods (Except required ones) are disabled.**

**Screenshots (Optional)**
![2022-09-17_15 22 53](https://user-images.githubusercontent.com/113802930/190879160-ef636b19-c413-4f6d-a9cb-ef99acdaefd4.png)

**Comment by henkelmax** [comment]
Which os are you using?

**Comment by isaiahcweener** [comment]
> Which os are you using?

I use Windows 10 though Apex Hosting which is the server host I use most likely uses a different OS.

**Comment by henkelmax** [comment]
Yeah, it seems that their servers does not meet the dependencies for LAME. There is not really much that can be done about that. You can use .wav files.

**Comment by isaiahcweener** [comment]
I was suspecting that it had something to do with their servers, oh well I can still use .wav files. Thanks for the help and for making the audio player mod.
