### ISSUE TITLE
Issues with filebin on 1.18.2 dedicated server.

### ISSUE THREAD

**Issue by SuperbNova11** [henkelmax/audio-player#21]
When uploading a .wav file to filebin it will go through the upload progress but once it gets to the part where it sends to the server it spits out the error "<!DOCTYPE html> <html> <head> <title>503 Backend fetch failed</title> </head> <body> <h1>Error 503 Backend fetch failed</h1> <p>Backend fetch failed</p> <h3>Guru Meditation:</h3> <p>XID: 82125227</p> <hr> <p>Varnish cache server</p> </body> </html>".

**Steps to reproduce the issue**
I am not sure. This may be an issue with just my files. I have tried this with renamed .mp3s, recorded as .wavs, and file transfers of .mp3s using Audacity.

**Expected behavior**
The .wavs being uploaded and I would be able to use them on the server

**Log files**
No Errors are found in the server log files. No crash happens it only shows on the filebin website.

**Versions**
- Minecraft version: 1.18.2
- Fabric loader version: 1.14.9
- Mod version: 1.0.3

**Other mods**
[modlist.txt](https://github.com/henkelmax/audio-player/files/9637907/modlist.txt)

**Screenshots (Optional)**
Screenshots of the issue.

I am sorry if this is just a problem on my end and I have wasted anytime.

**Comment by henkelmax** [comment]
Thats an issue with filebin. There are many other ways to upload files in 1.19+
But filebin is completely unassociated with this mod.
