### ISSUE TITLE
New Sound API in Fabric API 63 / 64

### ISSUE THREAD

**Issue by FixingGlobe** [henkelmax/audio-player#22]
This might be interesting. A new feature in the fabric api allows audio streaming, could be interesting for cds and maybe goat horns, or something else.

Add Sound API to allow sound instances to play custom audio streams (https://github.com/FabricMC/fabric/pull/2558) (Jonathan Coates)
https://github.com/FabricMC/fabric/pull/2558

It's just and interesting idea wich could be beneficial for the mod. The quilted fabric api also supports it, so no issues with compatibility.

Fabric api 64 just released, it's in the changelog for 63.
The changelog is listed in the second paragraph alongside the pull request.

**Comment by henkelmax** [comment]
I won't add any platfor specific implementations, since I'm using the same code on Forge, Fabric and Quilt.
