### ISSUE TITLE
Full Hopper under jukebox causes disk to dissapear

### ISSUE THREAD

**Issue by LarveyOfficial** [henkelmax/audio-player#25]
**Bug description**
If you have a hopper that is full and put a music disk in a jukebox above the hopper. It makes the music disk disappear

**Steps to reproduce the issue**
1. Place hopper
2. Fill hopper
3. Place jukebox over hopper
4. insert music disk
5. cry

**Expected behavior**
It should just keep playing until the hopper has an empty slot. OR it should keep playing until the song is over, THEN try to insert into the hopper, if its full then wait until the hopper has a slot left.

**Versions**
- Minecraft 1.19.2
- Fabric loader version 0.14.10
- Mod version 1.4.5

**Other mods**
- A list of the other mods that were installed when this problem occurred.
- It would be ideal if you could test if this problem persists when no other mod is installed.
- If not, please narrow down the mod(s) that are causing the problem.
- appleskin-fabric-mc1.19-2.4.1.jar
- architectury-6.3.56-fabric.jar
- badpackets-fabric-0.2.1.jar
- BlueMap-3.6-fabric-1.19.jar
- c2me-fabric-mc1.19.2-0.2.0+alpha.9.0.jar
- carpet-extra-1.19.2-1.4.84.jar
- carpet-fixes-1.19-1.12.2.jar
- cloth-config-8.2.88-forge.jar
- collective-fabric-1.19.2-5.16.jar
- Debugify-2.8.0.jar
- discerning-furnace-1.0.9+MC1.19-1.19.2.jar
- doubledoors-fabric_1.19.2-3.8.jar
- EditSign-1.19.2-2.6.0.jar
- fabric-api-0.68.0+1.19.2.jar
- fabric-carpet-1.19.2-1.4.84+v221018.jar
- FabricHomes-2.3.0.jar
- FabricTPA-3.2.1.jar
- FabricWarps-2.3.0.jar
- ferritecore-5.0.3-fabric.jar
- ftbbackups2-fabric-1.19.2-1.0.17.jar
- head-name-fix-1.19-1.2.0.jar
- krypton-0.2.1.jar
- lazydfu-0.1.3.jar
- lithium-fabric-mc1.19.2-0.10.2.jar
- memoryleakfix-1.19.1-0.7.0.jar
- minitweaks-1.19.2-1.3.3.jar
- NoChatReports-FABRIC-1.19.2-v1.13.12.jar
- servertick-mc1.19-1.7.jar
- starlight-1.1.1+fabric.ae22326.jar
- vmp-fabric-mc1.19.2-0.2.0+beta.7.0-all.jar
- voicechat-fabric-1.19.2-2.3.16.jar
- wthit-fabric-5.13.4.jar

**Comment by henkelmax** [comment]
Tested it and it works perfectly fine.
