### ISSUE TITLE
Add Create support

### ISSUE THREAD

**Issue by DanLCD** [henkelmax/audio-player#27]
**Is your feature request related to a problem? Please describe.**
Create features a mechanical arm that can automate certain tasks, one of them being playing a music disc by the arm pulling a disc out of a container and inserting it into a jukebox. This, however, plays the Minecraft music disc even if custom music had been put into the disc previously.

**Describe the solution you'd like**
For the jukebox to start playing the custom music just as it does when I insert a disc myself.

**Describe alternatives you've considered**
To not use Create functionality altogether, but I find this very limiting as Create helps maintain my contraptions compact.

**Comment by henkelmax** [comment]
Won't happen, sorry.

**Comment by DanLCD** [comment]
Bummer, but thanks anyways.
