### ISSUE TITLE
Putting the disc in a jukebox plays a brief sharp glitchy sound but the actual song

### ISSUE THREAD

**Issue by ChromaPIE** [henkelmax/audio-player#28]
**Bug description**
Described above. Goat horn failed to work too.
[Link to the filebin](https://filebin.net/32e6ff8c-b1ab-4795-9a3a-10ebe4e7d1c5). You can check if the song's alright. It's fine on my end.

**Steps to reproduce the issue**
1. Run `/audioplayer url` to start the process.
2. All the way ahead until the song's successfully etched to the disc.
3. Put the disc into the jukebox/Right click with the goat horn.
4. It goes *Tweet* like a machine bird.

**Expected behavior**
It plays the actual music.

**Versions**
- Minecraft version: 1.19.2
- Fabric loader version: 0.14.14
- Mod version: 1.4.5

**Other mods**
<details>
<summary>Mod list</summary>
<pre><code>
  [✔️] [Universal]Immersive Structures-2.0.7.jar
  [✔️] aas-1.19_1.3.1.jar
  [✔️] AdditionalStructures-1.19.x-(v.4.1.1).jar
  [✔️] Adorn-3.8.1+1.19.2-fabric.jar
  [✔️] advancements-enlarger-0.3.0-1.19.2.jar
  [✔️] AllSlabsToBlocks-1.19.2.jar
  [✔️] AmbientEnvironment-fabric-1.19.2-8.0+3.jar
  [✔️] AmbientSounds_FABRIC_v5.2.13_mc1.19.2.jar
  [✔️] another_furniture-fabric-2.1.2-1.19.2.jar
  [✔️] appleskin-fabric-mc1.19-2.4.1.jar
  [✔️] architectury-6.5.69-fabric.jar
  [✔️] armordamagescale-fabric-1.19.2-2.1.jar
  [✔️] arrp-0.6.4.jar
  [✔️] AttributeFix-Fabric-1.19.2-17.1.3.jar
  [✔️] audioplayer-1.19.2-1.4.5.jar
  [✔️] autohud-3.1+1.19.1.jar
  [✔️] auto-workstations-[MC1.19]-v1.0-SNAPSHOT-19.jar
  [✔️] balm-fabric-4.5.2+0.jar
  [✔️] BarteringStation-v4.0.3-1.19.2-Fabric.jar
  [✔️] bbs-1.19.2-1.1.0-fabric.jar
  [✔️] BetterAnimationsCollection-v4.0.5-1.19.2-Fabric.jar
  [✔️] betterbeds-1.2.0.jar
  [✔️] betterbiomeblend-1.19.0-1.3.6-fabric.jar
  [✔️] bettercombat-fabric-1.5.5+1.19.jar
  [✔️] betterfpsdist-fabric-1.19-2.4.jar
  [✔️] BetterThirdPerson-Fabric-1.19-1.9.0.jar
  [✔️] BOMD-1.4.6-1.19.2.jar
  [✔️] Bookshelf-Fabric-1.19.2-16.2.17.jar
  [✔️] BountifulFabric-4.0.0.jar
  [✔️] BowInfinityFix-1.19.x-fabric-2.5.0.jar
  [✔️] BridgingMod-1.19.2-1.2.0.jar
  [✔️] c2me-fabric-mc1.19.2-0.2.0+alpha.9.5.jar
  [✔️] cakechomps-fabric-6.0.0+1.19.2.jar
  [✔️] CameraOverhaul-1.4.0-fabric-universal.jar
  [✔️] cardinal-components-api-5.0.2.jar
  [✔️] carryon-fabric-1.19.2-2.0.4.6.jar
  [✔️] charmofundying-fabric-6.1.1+1.19.2.jar
  [✔️] chunksfadein-v3.0.8-1.19.jar
  [✔️] CITResewn-1.1.2+1.19.2.jar
  [✔️] clickadv-fabric-3.0.jar
  [✔️] clienttweaks-fabric-1.19-8.1.0.jar
  [✔️] cloth-api-4.0.65.jar
  [✔️] cloth-config-8.2.88-fabric.jar
  [✔️] Clumps-fabric-1.19.2-9.0.0+14.jar
  [✔️] collective-1.19.2-6.45.jar
  [✔️] combatroll-fabric-1.1.2+1.19.jar
  [✔️] comforts-fabric-6.0.3+1.19.2.jar
  [✔️] compact_storage_fabric-5.0.3_1.19.2.jar
  [✔️] configured-fabric-2.0.0-1.19.2.jar
  [✔️] Continents_1.19_v1.1.2.jar
  [✔️] continuity-2.0.1+1.19.jar
  [✔️] Controlling-fabric-1.19.2-10.0+7.jar
  [✔️] crack-physics-mod-pro-v121-fabric-1.19.2.jar
  [✔️] CraftingPad-1.19.2-1.0.10.jar
  [✔️] craftingtweaks-fabric-1.19-15.1.0.jar
  [✔️] CreativeCore_FABRIC_v2.9.3_mc1.19.2.jar
  [✔️] ctov-3.1.4.jar
  [✔️] ctov-bountiful-compat-1.0.jar
  [✔️] ctov-waystone-compat-1.0.jar
  [✔️] DamageTilt-1.19-fabric-0.1.2.jar
  [✔️] dashloader-4.1.3+1.19.jar
  [✔️] data-attributes-1.4.2.jar
  [✔️] death-counter-2022.10.5.jar
  [✔️] Debugify-2.8.0.jar
  [✔️] Decorative Blocks-fabric-1.19.2-3.0.0.jar
  [✔️] defaultoptions-fabric-1.19-15.0.0.jar
  [✔️] DisableCustomWorldsAdvice-3.0.jar
  [✔️] DistinguishedPotions-v4.0.1-1.19.2-Fabric.jar
  [✔️] doggo-mod-overhauled-1.0.1-1.19.2.jar
  [✔️] Droplight-1.19.2-fabric-1.0.5.jar
  [✔️] dungeon_difficulty-2.0.1+1.19.jar
  [✔️] DungeonsArise-1.19.2-2.1.54-fabric.jar
  [✔️] Durability101-fabric-1.19-0.0.4.jar
  [✔️] dynamiccrosshair-5.0+1.19.2-fabric.jar
  [✔️] dynamiccrosshair-compat-3.1+1.19.2.jar
  [✔️] eating-animation-1.9.jar
  [✔️] ecologics-fabric-1.19.2-2.1.11.jar
  [✔️] emeraldex-fabric1.19.x.jar
  [✔️] enchanting_table_descriptions-0.1.0+1.19.jar
  [✔️] EnchantingInfuser-v4.2.2-1.19.2-Fabric.jar
  [✔️] EnchantmentDescriptions-Fabric-1.19.2-13.0.14.jar
  [✔️] enhancedblockentities-0.7.2+1.19.2.jar
  [✔️] EnhancedVisuals_FABRIC_v1.5.9_mc1.19.2.jar
  [✔️] explorations-fabric-1.19.2-1.3.jar
  [✔️] explorify-fabric-1.19-1.3.0.jar
  [✔️] extractinator-fabric-1.19.2-2.0.1.jar
  [✔️] extrasounds-2.3.1+1.19.2-1.19.1.jar
  [✔️] fabric-api-0.73.2+1.19.2.jar
  [✔️] fabric-language-kotlin-1.9.1+kotlin.1.8.10.jar
  [✔️] fabric-release-regrowth-1.19-31.1.0.jar
  [✔️] fallingleaves-1.13.0+1.19.2.jar
  [✔️] fastback-0.7.4+1.19.2.jar
  [✔️] fastfurnace-1.19.2-5.jar
  [✔️] Fastload+1.19.2-2.6.11.jar
  [✔️] ferritecore-5.0.3-fabric.jar
  [✔️] FixMySpawnR-fabric-1.19.2-1.1.3.jar
  [✔️] ForgeConfigAPIPort-v4.2.10-1.19.2-Fabric.jar
  [✔️] FriendlyFire-Fabric-1.19.2-14.0.1.jar
  [✔️] friendsandfoes-beekeeperhut-fabric-mc1.19.2-1.2.0.jar
  [✔️] friendsandfoes-fabric-mc1.19.2-1.6.8.jar
  [✔️] ftb-library-fabric-1902.3.13-build.175.jar
  [✔️] ftb-quests-fabric-1902.4.8-build.190.jar
  [✔️] ftb-teams-fabric-1902.2.12-build.95.jar
  [✔️] fuelinfo-1.0.1+1.19.jar
  [✔️] geckolib-fabric-1.19-3.1.39.jar
  [✔️] guard-villagers-fabric-1.19.2-1.0.16.jar
  [✔️] handcrafted-fabric-1.19.2-2.0.2.jar
  [✔️] healingcampfire-1.19.2-5.1.jar
  [✔️] held-item-info-1.4.0.jar
  [✔️] hitmarker-1.18.2-3.1.jar
  [✔️] Iceberg-1.19.1-fabric-1.0.46.jar
  [✔️] IKnowWhatImDoing-4.1.1-fabric.jar
  [✔️] ImmediatelyFast-1.1.8+1.19.jar
  [✔️] immersive_weathering-1.19.2-1.2.7-fabric.jar
  [✔️] Incendium_v5.1.4_Hotfix.jar
  [✔️] indium-1.0.9+mc1.19.2.jar
  [✔️] IngameIME-fabric-1.19.2-1.6.6.jar
  [✔️] inventorypause-1.0.7.jar
  [✔️] iris-mc1.19.2-1.5.2.jar
  [✔️] item-filters-fabric-1902.2.9-build.46.jar
  [✔️] item-model-fix-1.0.3+1.19.jar
  [✔️] Jade-1.19.1-fabric-8.7.3.jar
  [✔️] JadeAddons-1.19.2-fabric-3.1.0.jar
  [✔️] jamlib-0.6.0+1.19.jar
  [✔️] journeymap-1.19.2-5.9.3-fabric.jar
  [✔️] Kambrik-4.0-1.19.2.jar
  [✔️] keepmysoiltilled-1.19.2-2.0.jar
  [✔️] kleeslabs-fabric-1.19-12.1.0.jar
  [✔️] krypton-0.2.1.jar
  [✔️] labels-1.19.2-1.7-fabric.jar
  [✔️] lambdabettergrass-1.3.0+1.19.jar
  [✔️] language-reload-1.5.4+1.19.2.jar
  [✔️] lazydfu-0.1.3.jar
  [✔️] LeavesBeGone-v4.0.1-1.19.2-Fabric.jar
  [✔️] letmedespawn-1.18.x-1.19.x-fabric-1.0.2.jar
  [✔️] lithium-fabric-mc1.19.2-0.10.4.jar
  [✔️] logcleaner-1.0.0.jar
  [✔️] lootr-1.19-0.4.25.64.jar
  [✔️] lowfire-fabric-1.19-3.0.0.jar
  [✔️] lunade-copper-pipe-1.12.jar
  [✔️] make_bubbles_pop-0.0.2-1.19.jar
  [✔️] marketcrates-fabric-1.5.jar
  [✔️] mcdw-5.0.4-1.19.jar
  [✔️] memoryleakfix-1.19.3-0.7.0.jar
  [✔️] MendableAnvils-fabric-1.19-1.0.0.jar
  [✔️] MerchantMarkers-1.19.1-fabric-1.2.3.jar
  [✔️] midnightlib-fabric-1.0.0.jar
  [✔️] mixintrace-1.1.1+1.17.jar
  [✔️] MobPlaques-v4.0.1-1.19.2-Fabric.jar
  [✔️] modmenu-4.1.2.jar
  [✔️] moonlight-1.19.2-2.2.7-fabric.jar
  [✔️] moreculling-1.19.1-0.16.0.jar
  [✔️] more-mobs-1.3.jar
  [✔️] moremobvariants-1.0.1-1.19.2.jar
  [✔️] MouseTweaks-fabric-mc1.19-2.22.jar
  [✔️] mousewheelie-1.10.7+mc1.19.2.jar
  [✔️] mvs-2.5.10-1.19.2.jar
  [✔️] mysticaloaktree-1.19.2-1.7-fabric.jar
  [✔️] naturalist-fabric-2.1.1-1.19.2.jar
  [✔️] nohostilesaroundcampfire-1.19.2-5.1.jar
  [✔️] notenoughanimations-fabric-1.6.2-mc1.19.2.jar
  [✔️] npc-variety-1.19.2-2.2.2.jar
  [✔️] Nullscape_v1.2a.jar
  [✔️] numismatic-overhaul-0.2.8+1.19.jar
  [✔️] nyfsquiver-Fabric-0.5.1-1.19.2.jar
  [✔️] OpenLoader-Fabric-1.19.2-15.0.1.jar
  [✔️] overweightfarming-1.19.2-2.0.2-fabric.jar
  [✔️] owo-lib-0.9.3+1.19.jar
  [✔️] oxidized-1.7.2.jar
  [✔️] packages-fabric-1.19.2-3.4.jar
  [✔️] passiveshield-1.19.2-3.1.jar
  [✔️] Philips-ruins1.19.2-4.6[Fabric].jar
  [✔️] phosphor-fabric-mc1.19.x-0.8.1.jar
  [✔️] player-animation-lib-fabric-0.4.2.jar
  [✔️] playerex-3.5.2.jar
  [✔️] polymorph-fabric-0.46.1+1.19.2.jar
  [✔️] PresenceFootsteps-1.6.4.jar
  [✔️] Prism-1.19.2-fabric-1.0.3.jar
  [✔️] projectile_damage-fabric-3.0.0+1.19.jar
  [✔️] PuzzlesLib-v4.3.12-1.19.2-Fabric.jar
  [✔️] questsadditions-fabric-1.19.2-1.4.1.jar
  [✔️] raised-fabric-1.19.2-1.1.4.jar
  [✔️] realisticbees-1.19.2-3.2.jar
  [✔️] realisticsleep-1.7.0.jar
  [✔️] redstructure-1.0.5-fabric-1.19.2.jar
  [✔️] reeses_sodium_options-1.4.9+mc1.19.2-build.67.jar
  [✔️] relicex-3.2.7.jar
  [✔️] repurposed_structures_fabric-6.1.6+1.19.2.jar
  [✔️] rer-2.6.0.jar
  [✔️] resourcefulconfig-fabric-1.19.2-1.0.19.jar
  [✔️] resourcefullib-fabric-1.19.2-1.1.22.jar
  [✔️] right-click-harvest-3.1.0+1.19-1.19.2.jar
  [✔️] rocks-1.6.1.jar
  [✔️] RoughlyEnoughItems-9.1.587.jar
  [✔️] RoughlyEnoughLootTables-1.19-1.0.jar
  [✔️] RoughlyEnoughProfessions-fabric-1.19.2-1.1.3.jar
  [✔️] ruined-equipment-2.0.0+1.19.jar
  [✔️] servercore-1.3.3-1.19.2.jar
  [✔️] ShoulderSurfing-Fabric-1.19.2-2.3.0.jar
  [✔️] show-me-your-skin-1.3.7+1.19.jar
  [✔️] shroomdealers_1.6-1.19.2-fabric.jar
  [✔️] simplyswords-fabric-1.42.1-1.19.2.jar
  [✔️] SkyVillages-1.0.2.1-1.19.x-fabric.jar
  [✔️] slight-gui-modifications-2.3.0.jar
  [✔️] slimyfloor-1.19.1-1.2.5.jar
  [✔️] smarterfarmers-1.19.2-1.7.1-fabric.jar
  [✔️] Smooth Swapping 0.6 (1.19.2)-0.6.jar
  [✔️] smoothboot-fabric-1.19-1.7.1.jar
  [✔️] smoothchunk-fabric-1.19.1-2.0.jar
  [✔️] SmoothScrollingEverywhere-3.0.5.jar
  [✔️] sodium-extra-0.4.16+mc1.19.2-build.90.jar
  [✔️] sodium-fabric-mc1.19.2-0.4.4+build.18.jar
  [✔️] soundphysics-fabric-1.19.2-1.0.18.jar
  [✔️] spawn-animations-1.8.2.jar
  [✔️] spelunkery-1.19.2-0.1.11-fabric.jar
  [✔️] spoornarmorattributes-2.0.8-1.19-fabric.jar
  [✔️] spoornweaponattributes-4.0.9-1.19-fabric.jar
  [✔️] stack-to-nearby-chests-mc1.19.2-0.2.6.jar
  [✔️] stb-5.0.0+1.19-fabric.jar
  [✔️] stepup-1.19.1-fabric0.58.5-1.1.jar
  [✔️] Structory_Towers_1.19_v1.0.1.jar
  [✔️] Structory-1.19-v1.3.jar
  [✔️] StylishEffects-v4.3.2-1.19.2-Fabric.jar
  [✔️] supplementaries-1.19.2-2.2.49-fabric.jar
  [✔️] takesapillage-1.19-1.0.4.jar
  [✔️] taptab-1.19.2-1.1.0.jar
  [✔️] TaxFreeLevels-1.3.3-fabric-1.19.jar
  [✔️] TerraBlender-fabric-1.19.2-2.0.1.136.jar
  [✔️] Terralith_v2.3.6.jar
  [✔️] The_Graveyard_2.3_(FABRIC)_for_1.19.2.jar
  [✔️] The_Graveyard_Biomes_1.6_(FABRIC)_for_1.19.2.jar
  [✔️] toms_storage_fabric-1.19-1.5.0.jar
  [✔️] Towns-and-Towers-v.1.10.1-FABRIC-1.19.2.jar
  [✔️] Trajectory Preview-2.0-1.18.2.jar
  [✔️] transportables-1.2.1.jar
  [✔️] trashslot-fabric-1.19-12.0.1.jar
  [✔️] TravelersTitles-1.19.2-Fabric-3.1.0.jar
  [✔️] TreeChop-1.19.2-fabric-0.17.3.jar
  [✔️] trinkets-3.4.2.jar
  [✔️] Tumbleweed-fabric-1.19-0.5.1.jar
  [✔️] UniversalEnchants-v4.2.15-1.19.2-Fabric.jar
  [✔️] unstructured-0.5.3+1.19.2.jar
  [✔️] villagernames-1.19.2-4.2.1.jar
  [✔️] visuality-0.5.5.jar
  [✔️] voicechat-fabric-1.19.2-2.3.28.jar
  [✔️] Wabi-Sabi-Structures-1.1.2-Fabric.jar
  [✔️] walljump-unofficial-1.6.1b-all+1.19.2.jar
  [✔️] wanderingcollector-1.1.3+mc1.19.jar
  [✔️] waystone_towers-1.19.2-FABRIC-1.0.8.jar
  [✔️] waystones-fabric-1.19-11.1.0.jar
  [✔️] wmitaf-fabric-mc1.19-3.1.1.jar
  [✔️] YetAnotherConfigLib-2.2.0-for-1.19.2.jar
  [✔️] youre-in-grave-danger-1.4.8.jar
  [✔️] YungsApi-1.19.2-Fabric-3.8.2.jar
  [✔️] YungsBetterDesertTemples-1.19.2-Fabric-2.2.1.jar
  [✔️] YungsBetterDungeons-1.19.2-Fabric-3.2.1.jar
  [✔️] YungsBetterMineshafts-1.19.2-Fabric-3.2.0.jar
  [✔️] YungsBetterStrongholds-1.19.2-Fabric-3.2.0.jar
  [✔️] YungsBetterWitchHuts-1.19.2-Fabric-2.1.0.jar
  [✔️] YungsBridges-1.19.2-Fabric-3.1.0.jar
  [✔️] YungsExtras-1.19.2-Fabric-3.1.0.jar
</code></pre>
</details>

**Comment by henkelmax** [comment]
Please fill out the bug template and provide logs, as well as the file you tried to play.

**Comment by ChromaPIE** [comment]
Follow up: Just removed all symbols from the file name, leaving only `ceilings`, it worked just fine.

**Comment by henkelmax** [comment]
Yeah the mod is very picky about the audio format

**Comment by ChromaPIE** [comment]
Also seems like the song downloaded will be automatically  cropped to the set duration in the config file. It will be a little confusing bc there lacks a warning about this. So I'm thinking if we can get a warning in chat if the song exceeded the set maximum duration, or simply mention it in the description on modrinth & curseforge.

**Comment by henkelmax** [comment]
This is not the case. The server saves the file you upload, exactly like it is without modification.

**Comment by ChromaPIE** [comment]
I remember checking the music file and found that it got cropped to 1 minute. maybe smth messed up my memory. It's working just fine now. Thanks for all the support!
