### ISSUE TITLE
No sound when playing.

### ISSUE THREAD

**Issue by Yamadaisme** [henkelmax/audio-player#30]
**Bug description**

**Steps to reproduce the issue**
1. Using filebin to upload the music
2. Download the music in the game
3. Add the music to the music disc item
4. No sound of music when playing on the jukebox

**Expected behavior**
It should play the sound

**Log files**
Please provide log files of the game session in which the problem occurred.
Don't paste the complete logs into the issue. 
You can use [https://gist.github.com/](https://gist.github.com/).

**Versions**
- Minecraft version: 1.19.2
- Fabric loader version: 0.14.14
- Mod version: 1.4.5

**Other mods**
I'm playing on the Better MC fabric modpack: https://www.curseforge.com/minecraft/modpacks/better-mc-fabric

**Screenshots (Optional)**
Screenshots of the issue.

**Comment by henkelmax** [comment]
Please provide logs and a recording of this happening in game.

**Comment by Valdblade** [comment]
I have the same issue as of first installation https://pastebin.com/KfQiF5W5 this is the only wrror the console shows

**Comment by Valdblade** [comment]
https://drive.google.com/file/d/1VgnSaAikrcONkWJqnBp49tC8-dxXA6MJ/edit
the recording happening in game. I have also tried via the serverfile file feature without any work @henkelmax

**Comment by henkelmax** [comment]
> I have the same issue as of first installation https://pastebin.com/KfQiF5W5 this is the only wrror the console shows

This is not relevant. I need the full logs

> https://drive.google.com/file/d/1VgnSaAikrcONkWJqnBp49tC8-dxXA6MJ/edit the recording happening in game. I have also tried via the serverfile file feature without any work @henkelmax

Can you send me the audio file you uploaded?

**Comment by Valdblade** [comment]
https://pastebin.com/YCQ4zgxx full logs 

https://www.dropbox.com/s/omuzjhfr5ix97z1/bassglide.mp3?dl=0 audio file used

**Comment by henkelmax** [comment]
> https://pastebin.com/YCQ4zgxx full logs
> 
> https://www.dropbox.com/s/omuzjhfr5ix97z1/bassglide.mp3?dl=0 audio file used

There is no player joining the game in your logs

Please try if it works when you convert your file to .wav

**Comment by Valdblade** [comment]
Trying it

**Comment by Valdblade** [comment]
ok wav works. Also smth else i noticed, if you play an mp3 file it crashes the plugin and the wav files wont work after that. Which will make you restart the server thus re-enabling the plugin and making wav work

**Comment by henkelmax** [comment]
Try putting your .mp3 file in an audio tool like Audacity and export it as .mp3 again. Sometimes audio files are in a broken format.

**Comment by Valdblade** [comment]
ok one sec

**Comment by Valdblade** [comment]
ok now it worked. That was weird

**Comment by henkelmax** [comment]
Yes, this happens when you have a mp3 file that is not supported by the mp3 decoder of the voice chat mod.

**Comment by Valdblade** [comment]
makes sense. Thank you for the help
