### ISSUE TITLE
Failed to download sound: No mp3 or wav files uploaded when the uploaded file was a mp3 or wav

### ISSUE THREAD

**Issue by Woolenracketeer** [henkelmax/audio-player#32]
I'm trying to make a custom horn in a server i play on that has simple voice chat and audioplayer set up but when i try uploading a file even when it is a mp3 or a wav file it says there are no mp3 or wav files uploaded, when I tried using the URL command with dropbox like the featured video shown it also did not work, it claimed it was an invalid file format. When I try looking up any issues I dont see any solutions to this.

**Comment by henkelmax** [comment]
Please fill out the bug template
