### ISSUE TITLE
Modified discs playing vanilla sounsd

### ISSUE THREAD

**Issue by IMT07** [henkelmax/audio-player#37]
**Bug description**
So we have the mod on our server, and I used it to add more ambience to my base. but sometimes the discs play the vanilla sounds instead of the bird sounds I uploaded. I don't know exactly why, but I think it's after the modified sounds have been played and the disc is still in the jukebox

**Steps to reproduce the issue**
1. upload a sound via filebin
2. apply it to a disc
3. play it
**Expected behavior**
It plays the new added sound

**Log files**
it isn't my server so no access to files

**Versions**
- 1.19.2
- Fabric loader 1.19.2 0.14.10
- 1.19.2-2.4.0

**Other mods**
Simple Voicechat
Enhanced Groups
Fabric api
FerriteCore
itemswapper
krypton
lazydfu
starlight
vcinteraction

**Comment by henkelmax** [comment]
Please send me your server logs

**Comment by KhaozFrost** [comment]
I've been getting this same thing. 
Tested it with a 5 1/2 min disc and a 1hr disc; the moment the original disc's timer (what you linked it with ends (the time it takes for the disc to finish its vanilla soundtrack, it will start playing again ontop of the custom sound)

**Comment by henkelmax** [comment]
> I've been getting this same thing. Tested it with a 5 1/2 min disc and a 1hr disc; the moment the original disc's timer (what you linked it with ends (the time it takes for the disc to finish its vanilla soundtrack, it will start playing again ontop of the custom sound)

Does this happen for you in 1.19.4?

**Comment by KhaozFrost** [comment]
> > I've been getting this same thing. Tested it with a 5 1/2 min disc and a 1hr disc; the moment the original disc's timer (what you linked it with ends (the time it takes for the disc to finish its vanilla soundtrack, it will start playing again ontop of the custom sound)
> 
> Does this happen for you in 1.19.4?

not been tested with 1.19.4 since cobblemon is still running 1.19.2

**Comment by KhaozFrost** [comment]
here is a link to a 1hr song though. after a set amount of time it'll start playing the vanilla disc music
https://www.mediafire.com/file_premium/dpb2sdvu4wjd66u/Pok%25C3%25A9mon_Lofi_Music_1_Hour_Mix_%2528Part_1%2529.mp3/

**Comment by IMT07** [comment]
oh sorry for not reacting, just found the post again XD. I think its because the disc get repeated, so if the song is longer than the duration of the disc it will start again, but then with the vanilla sound or smth
