### ISSUE TITLE
SBM Jukebox Compatibility Issue

### ISSUE THREAD

**Issue by 8RavenPhoenix8** [henkelmax/audio-player#38]
**Bug description**
Using Audioplayer with SBM Jukebox causes hoppers to behave according to how Audioplayer tells them to and not SBM Jukebox. Changing the Audioplayer config settings related to jukeboxes and hoppers/dispensers to false and then using it with SBM Jukebox allows the music disc to play when a jukebox is above an unlocked hopper, however, the music disc disappears. If you look at the jukebox with a mod like Jade it'll show it as "empty" even though you'll hear the music disc play. Also, if you try to remove the music disc from the jukebox at this point you will not get the disc back. If you let the song play to the end, the music disk will not be in the hopper as it should be according to SBM Jukebox.

**Steps to reproduce the issue**
1. Download both Audioplayer and SBM Jukebox
2. Create and enter a world
3. Place a jukebox above a hopper
4. Put a music disc into the hopper
5. The music disc will enter the hopper immediately as it does with Audioplayer alone instead of the hopper only taking the disc when the song is over like when using SBM Jukebox alone

OR:

1. Download both Audioplayer and SBM Jukebox
2. Change "jukebox_hopper_interaction=true" to "jukebox_hopper_interaction=false" and "jukebox_dispenser_interaction=true" to "jukebox_dispenser_interaction=false" in the Audioplayer config and save
3. Create and enter a world
4. Place a jukebox above a hopper
5. Put a music disc into the hopper
6. The music disc will play but if you try to remove the music disc from the jukebox you will get no music disc and when the song ends there will be no music disc in the hopper

**Expected behavior**
I expected that either SBM Jukebox would overwrite Audioplayer's hopper/dispenser/jukebox adjustments and allow a music disc to play through the end before being taken by a hopper, or changing the config file settings of Audioplayer would let hoppers behave according to SBM Jukebox rules. I would like to be able to create an automatic jukebox, for context, which you can do in Java using SBS Jukebox, but I would also like to be still able to use Audioplayer.

**Log files**
https://gist.github.com/8RavenPhoenix8/43e93f1d1b1731c30e3ffeae42925d35#file-log-txt(https://gist.github.com/).

**Versions**
- 1.19.2
- 0.14.19
- 1.19.2-1.4.5

**Other mods**
SBM Jukebox 1.0.7

**Comment by henkelmax** [comment]
Sorry, but we moved on to 1.19.4.
This version won't receive any updates anymore.
