### ISSUE TITLE
Music download to server fails - but only sometimes

### ISSUE THREAD

**Issue by Tobias-Jung-DHBW** [henkelmax/audio-player#4]
**Bug description**
I have more than 50 sound files on the server, but 2 failed to play music and stopped instantly. After digging around i found out, that the sound files on the server are 0 seconds long (there seems to be a tiny bit of audio thou)

After renaming the files locally on my computer and uploading them via SFTP to my server and replacing the broken ones, the song works perfectly. 

Therefore it seems to be a bug related to filebin to server download failing.

Around 90% of songs work thou without problems. 
They were all converted using audacity the same way with the same bitrate, hence there should be no issues there. 

**Steps to reproduce the issue**
1. Upload a song
2. Let the server download it
3. Try to play it
4. And audio stops instantly, just title is displayed

**Expected behavior**
No crash logs, no log that upload fails, just 0 sekonds long on the server, if i download the just uploaded song from filebin, it works and sounds totally fine.

**Log files**
There are no crash logs in console... 😢 

**Versions**
- 1.18.2
-  0.13.3
- audioplayer 1.18.2-1.0.2

**Other mods**
	- audioplayer 1.18.2-1.0.2
	- bluemap 1.7.2
	- cardinal-components-base 4.0.0 via fabrichomes
	- cardinal-components-entity 4.0.0 via fabrichomes
	- cardinal-components-world 4.0.0 via fabricwarps
	- carpet 1.4.66
	- carpet-extra 1.4.64
	- cloth-basic-math 0.6.0 via cloth-config
	- cloth-config 6.1.48 via editsign
	- mcdiscordchat
	- editsign 2.2.7
	- fabric 0.47.10+1.18.2
	- worldedit
	- fabrichomes 2.2.0
	- fabricloader 0.13.3
	- fabricwarps 2.2.0
	- fallingtree 3.3.0
	- java 17
	- lazydfu 0.1.2
	- ledger 1.2.4
	- lithium 0.7.9
	- luckperms 5.3.98
	- mcdiscordchat 1.18-2.0.0-alpha.1
	- mcxr-core 0.1.1
	- minecraft 1.18.2
	- net_dv8tion_jda 5.0.0-alpha.9 via mcdiscordchat
	- net_sf_trove4j_trove4j 3.0.3 via mcdiscordchat
	- org_apache_commons_commons-collections4 4.4 via mcdiscordchat
	- org_jetbrains_kotlin_kotlin-reflect 1.6.10 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib 1.6.10 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.6.10 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.6.10 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.5.2 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.5.2 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.3.1 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.3.1 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.3.1 via fabric-language-kotlin
	- org_joml_joml 1.10.2 via mcxr-core
	- org_json_json 20220320 via mcdiscordchat
	- packet_tweaker 0.2.0+1.18-pre1 via server_translations_api
	- placeholder-api 1.1.3+1.17.1 via styledplayerlist
	- player-data-api 0.1.0+1.18 via styledplayerlist
	- rightclickharvest 2.0.0
	- server_translations_api 1.4.9+1.18.2-rc1 via ledger
	- styledplayerlist 2.1.3+1.18
	- voicechat 1.18.2-2.2.26
	- worldedit 7.2.10+1742f98
	
	
Could recreate same issue with only fabric api, simple voice chat and audio player

**Comment by henkelmax** [comment]
Can you send me the broken file?
Please also send me your server logs?

**Comment by Faolon12** [comment]
I get this exact same issue, also with just fabric api, voice chat and audio player. if you need the files, let me know where they are please. as im not sure which ones you want, or where they are.

**Comment by henkelmax** [comment]
The logs are at `logs/latest.log`
and the audio files are stored at <your-world-folder>/audio_player_data/<some-id>.wav
please also provide the file you uploaded to filebin.

Does this only happen for a specific audio file or does it happen randomly?

**Comment by Faolon12** [comment]
Ok, so i THINK i figured out the issue. If i natively download a .wav lets say a song called A.Wav, it will work, flawlessly, (i havent downloaded enough to see random) but if i use a converter to convert a song from.something to .wav, then it gets issues, I was using a few online converters, So, i tested throwing in those same mp3-.ogg files whatever, into fl studio, then i exported them as .wav, and left default values. then it worked. i think the converters in general are giving a weird encoding on the ,wav's
Encoding and stuff i have is below.

![Screenshot 2022-04-27 095336](https://user-images.githubusercontent.com/38812616/165560242-e055fed4-724e-4951-aa26-9f08fbabfa47.png)
https://filebin.net/b84b8f00-c8ed-4d7e-9924-7dad55afd80c


Above is broken filebin, the downloaded.wav file is weird,
Below is when i use a proper program like fl studio to convert a file,
https://filebin.net/62b7e2ce-3e3c-4b4b-9427-31b49171b17f
All filebins seem fine, till minecraft tries to download them. then only original.wav is supported (depends on encoding, and/or a conversion to .wav with default in fl studio.)

wav, and log file. https://drive.google.com/file/d/1OweCupgar3OLw0qWdIj1kFked8kXO0cl/view?usp=sharing

still not entirely sure if this is the issue, as i did run into a slight random issue where a online converter did work for one song, but im not sure what the encoding on it was when it was a mp3, so it may still have been encoding, but this one was good from the bat.

**Comment by Faolon12** [comment]
yeah, did a few more songs, through fl studio conversion they always work. I think its a encoding issue, but not sure if its like bitrate or something else.

**Comment by henkelmax** [comment]
Alright, thank you for testing this!
I will further investigate this issue.
