### ISSUE TITLE
Permissions That Work with Luckperms

### ISSUE THREAD

**Issue by corfoto4** [henkelmax/audio-player#42]
**Is your feature request related to a problem? Please describe.**
Looking to control who has permission to access /audioplayer

**Describe the solution you'd like**
Have permission nodes that work with Luckperms

**Describe alternatives you've considered**
Tried using the op perms, but I want different levels of people who can use the command

**Comment by henkelmax** [comment]
Closed with 4e1b2277dc420a15b0f4baa77c1cc9ebfde7615a
