### ISSUE TITLE
Use audio-player on Spigot servers

### ISSUE THREAD

**Issue by ZaHecc** [henkelmax/audio-player#44]
**Is your feature request related to a problem? Please describe.**
I'd like to use this fabric mod as a plugin such as the simple voice mod is used.

**Describe the solution you'd like**
Possible rework so it can be used as a plugin and used on Spigot servers with plugins.

**Describe alternatives you've considered**
I've tried installing it as a plugin and it doesn't work. I'm not sure what the solution would be other then seeing if it was possible to be made/used as a plugin

**Additional context**
Thanks for your work!

**Comment by henkelmax** [comment]
There already is a plugin
