### ISSUE TITLE
Ability to play streams ("web radio")

### ISSUE THREAD

**Issue by vico93** [henkelmax/audio-player#46]
Basically, allow the url parameter to accept stream address and not only standalone files.

This way this mod would be a good replacement for the old [OpenFM](https://github.com/PC-Logix/OpenFM) ([CF](https://www.curseforge.com/minecraft/mc-mods/openfm)) mod.

**Comment by henkelmax** [comment]
This could be a separate mod, but won't be a feature of this one.
