### ISSUE TITLE
Can't upload with filebin.

### ISSUE THREAD

**Issue by FearDragon** [henkelmax/audio-player#48]
**Bug description**
I try to upload a 1.3MB mp3 file and filebin gives the error "Insufficient Storage".

**Steps to reproduce the issue**
1. type /audioplayer upload
2. Click on 'this link'
3. upload file

**Expected behavior**
Should upload the file

**Log files**
No log files

**Versions**
- 1.19.4
- 0.14.21
- 1.5.2

**Other mods**
audioplayer-1.19.4-1.5.2.jar
carpet-extra-1.19.4-1.4.100.jar
fabric-api-0.83.0+1.19.4.jar
fabric-carpet-1.19.4-1.4.101+v230319.jar
ferritecore-5.2.0-fabric.jar
gottagofast-1.0.2.jar
krypton-0.2.2.jar
lithium-fabric-mc1.19.4-0.11.1.jar
memoryleakfix-fabric-1.17+-1.1.1.jar
smoothchunk-fabric-1.19.4-3.0.jar
starlight-1.1.1+fabric.ae22326 (1).jar
viewdistancefix-1.19.4-1.0.0.jar
voicechat-fabric-1.19.4-2.4.13.jar

**Screenshots (Optional)**
Screenshots of the issue.

**Comment by henkelmax** [comment]
Thats not an issue with the mod. Thats just filebin being on its storage limit.

**Comment by ChritizinGaming** [comment]
> Thats not an issue with the mod. Thats just filebin being on its storage limit.

Hi Henkelmax

Do you have a solution for it?

**Comment by henkelmax** [comment]
Host your own filebin instance or use any other upload method.

**Comment by ChritizinGaming** [comment]
> Host your own filebin instance or use any other upload method.

Thank you for getting back to me :)

Could you be so kind to take the time and explain to me how to make my own filebin instance? 

Because choosing another upload, like Dropbox, isn't an option.

Thank you in advance.
