### ISSUE TITLE
Jukebox plays multiple songs at once. Keeps playing when Jukebox is broken

### ISSUE THREAD

**Issue by Ebsolas** [henkelmax/audio-player#5]
**Bug description**
Jukebox was glitched into playing multiple records when discs are placed in too quickly.

**Steps to reproduce the issue**
1. Go into creative mode (easier to replicate)
2. Place down a jukebox
4. While holding a disc, Rapid r-click on the jukebox with the disc (macro recommended)
5. The jukebox will now be playing multiple instances of the same song.
6. R clicking again will eject the disc, but the music will keep playing
7. Continuing to insert discs will increase the number of songs played
8. Breaking the jukebox will cause the disc music to continue being played without a jukebox
9. Exiting world and re-entering fixes it until the steps are followed again

**Expected behavior**
It is expected that when discs are clicked rapidly on a jukebox it'll emulate vanilla behavior where the disc is ejected on the second click. Further clicks alternate between inserting the held disc and ejecting the inserted one.

**Versions**
- Minecraft version: 1.18.2
- Fabric loader version: 0.13.3 & 0.14.3 (2 versions tested)
- Mod version: 1.18.2-1.0.2

**Other mods**
Fabric API 0.48.0 & 0.51.1 (dependency, 2 versions tested)
Voice chat mod 1.18.2-2.2.32 & 1.18.2-2.2.37 (dependency, 2 versions tested)
AudioPlayer (from curseforge)

**Comment by henkelmax** [comment]
This also happens in vanilla Minecraft. This is not a bug of this mod.
