### ISSUE TITLE
Using a dropper to place a disc when one is still playing in a jukebox duplicates the playing disc

### ISSUE THREAD

**Issue by NoThrottle** [henkelmax/audio-player#51]
**Bug description**
Using the "dropper, hopper, etc" method to play a disc has a bug wherein if a disk is already playing and you try to dropper a disc into it, it will duplicate the disc (placing it into the dropper)

**Steps to reproduce the issue**
1. Place a dropper facing a jukebox
2. Place disc A in a dropper
3. Play disc B in the jukebox
4. Power the dropper
5. A duplicate of disc B will appear in the dropper

**Expected behavior**
A. The dropper simply wont do anything
B. Force the jukebox to stop and play the next disc.

**Versions**
- 1.19.4 version
- 0.14.21 version
- 1.5.2 version

**Other mods**
Occurs without other mods

**Comment by henkelmax** [comment]
Can't confirm.
The dropper functionality is also not implemented by the mod anymore. This is vanilla Minecraft.
