### ISSUE TITLE
play command doesn't have a way to stop it

### ISSUE THREAD

**Issue by ShiftySpace** [henkelmax/audio-player#56]
**Bug description**
Thank you so much for adding the play command to the audio player, been very great to have. The only issue is there's now no way to stop the sound from playing besides waiting for the audio to end.

**Steps to reproduce the issue**
ex: `/audioplayer play (sound id) x y z 10`
There is now no way to stop the sound

**Expected behavior**
Minecraft has the /stopsound command, it could work similar to that. I'd expect something like `/audioplayer stop (sound id)` and it would stop the nearest sound with that id. And or `/audioplayer stop (sound id) x y z` to stop it playing from the specified coordinates.

**Versions**
- Simple Voice Chat version: 1.20.1-2.4.22
- Minecraft version: 1.20.1
- Fabric loader version: 0.14.21
- Mod version: 1.20.1-1.6.2

**Comment by ShiftySpace** [comment]
Figured out that the "other" category can change the volume so that works out. If you allow the pull request I sent to add the stop command than this issue is fixed.

**Comment by ShiftySpace** [comment]
Accidentally closed the issue. 

Realized you can change the volume with the "other" category in game. So that is resolved.

If you allow the code I put in the pull request this issue is fixed.

**Comment by SmajloSlovakian** [comment]
i made another pull request, which repairs/updates the ShiftySpace's code so it works now... can you please check it out?

**Comment by henkelmax** [comment]
Closed with #66
