### ISSUE TITLE
Custom disk volume seems not to be editable via noteblock & jukebox volume

### ISSUE THREAD

**Issue by Wolphwood** [henkelmax/audio-player#60]
**Bug description**
The volume of music played in the jukebox is not on the jukebox channel, so you can't adjust the volume on the player side.

**Steps to reproduce the issue**
1. Play custom music
2. Try to change volume

**Expected behavior**
The volume of the custom disk must play on jukebox channel

**Versions**
- voicechat fabric 2.4.13.jar
- Minecraft 1.20.1
- audioplayer 1.7.1

**Comment by henkelmax** [comment]
It is called music discs, not jukebox.
![image](https://github.com/henkelmax/audio-player/assets/13237524/05b035ad-3752-4b51-a077-ecd5f0ee8d8b)

**Comment by Wolphwood** [comment]
Oh.. I've searched every menu but this one...
I forget it all the time

sorry to have bothered you
