### ISSUE TITLE
Parrots do not dance to custom music discs

### ISSUE THREAD

**Issue by ThisGreenDingo** [henkelmax/audio-player#63]
When playing a custom music disc, parrots will not dance to the music. 

Steps to reproduce the issue:
1. Play a vanilla music disc
2. The parrot will dance
3. Play a custom music disc
4. The parrot will not dance

Expected behavior:
Parrots should dance to custom music discs, unless a tag is applied to tell them otherwise.

Version: [FABRIC][1.20.1] AudioPlayer 1.20.1-1.8.3

**Comment by henkelmax** [comment]
Unfortunately that's impossible without client-side modifications.
