### ISSUE TITLE
Configurable Custom Disc Range Modifier

### ISSUE THREAD

**Issue by RogueSnowMan** [henkelmax/audio-player#65]
**Feature Request**
the ability to configure the shape of the "audio bubble" of the Configurable music disc range
and Per-item custom music disc range.

**Expected behavior**
the configurable range is, :- example 64x64 or 32x32 blocks, 
Would it be possible to also configure the size and shape, example :- 64x32 or 16x24 blocks

**Versions**
- Mod version :- Version: [FABRIC][1.20.1] AudioPlayer 1.20.1-1.8.3+

**Comment by henkelmax** [comment]
This already exists.

**Comment by RogueSnowMan** [comment]
sorry i was unaware, i looked but found nothing refering to it, appologies

**Comment by henkelmax** [comment]
![image](https://github.com/henkelmax/audio-player/assets/13237524/68221534-c65c-4889-9ae6-e24796328a07)

**Comment by RogueSnowMan** [comment]
ah yes, i thought that was just for a set size, example :- a 64x64 sphere
does that allow for altering the shape of the sphyere, example 64x32 sphyrical shape

**Comment by henkelmax** [comment]
No, only distance. A square range is not possible, since sound can't travel further on diagonals. This wouldn't make sense at all.
