### ISSUE TITLE
Forge support for AudioPlayer?

### ISSUE THREAD

**Issue by CarlRyds** [henkelmax/audio-player#68]
Hey,

Does the AudioPlayer mod work with Forge/Bukkit/Spigot/Paper servers as the main Simple Voice Chat mod does?

If not, do you have any plans to bring it to Forge? I hate that the community is forced to pick between Fabric or Forge, with some mods only working on one or the other.

Also, Will discs already made on a Fabric server, which is moved to a Paper server, still work?
e.g will they still play without the mod if there are pre-existing discs?

Thanks

**Comment by henkelmax** [comment]
There is only a Fabric version of this mod. The Bukkit version is a third-party port and is not compatible.

**Comment by CattopyTheWeb** [comment]
@henkelmax Do you plan on making a forge version of this mod?
