### ISSUE TITLE
Files over 5 minutes don't play on music discs

### ISSUE THREAD

**Issue by VeryKitty03** [henkelmax/audio-player#71]
### Bug description

So, I tried to get a version of Please Hold by Jono in a music disc (5 minutes and 6 seconds), but when I tried to play it, it did not work.  Are files over 5 minutes not supported?  If so, can this be changed?

### Minecraft version

1.20.4

### Simple Voice Chat version

1.20.4-1.0.5

### Mod version

1.20.4-1.8.9

### Mod loader and version

Fabric Loader 0.15.7

### Steps to reproduce

It does this on any version on 1.20.4, as far as I'm aware.  So, use filebin or server files to import the audio.  Then, proceed as usual and put it on a music disc.  Try to play it then and see it it works.  It might just be too long.

### Expected behavior

I expected the disc to play, but instead, it showed the music note particles for about 2 seconds and stopped.  No sound was played.

### Log files

12.03 19:56:25 [Server] AudioPlayerThread/WARN Error converting mp3 file with native decoder 12.03 19:56:27 [Server] AudioPlayerThread/ERROR Audio 33af2a7f-d7c7-4dc7-9ad0-a1171823aedd was too long to play

### Screenshots

I can't screenshot the issue, it is not visual.

**Comment by henkelmax** [comment]
This can be changed in the config. But please avoid setting it to a very high value, as big audio files will cause delays and a high RAM usage. But if you set it to 6 mins, that should be fine.
