### ISSUE TITLE
Audio is too long to play

### ISSUE THREAD

**Issue by creeloper27** [henkelmax/audio-player#72]
### Bug description

I tried to play an mp3 that is 2:25 minutes long and I got the error `Audio is too long to play`, this should totally get extended to be more reasonable if possible.
Also the actual maximum allowed should get added to the description of the mod.

### Minecraft version

1.20.1

### Simple Voice Chat version

2.5.9

### Mod version

1.8.9

### Mod loader and version

Fabric Loader 0.15.7

### Steps to reproduce

1. use `/audioplayer url URL` with an URL pointing to an mp3 audio file of around 2:30 minutes
2. load the audio in a horn
3. get the error

### Expected behavior

The audio should play

### Log files

not relevant

**Comment by henkelmax** [comment]
You can change the maximum duration in the config. But i would NOT recommend doing that for the goat horn, as you can't stop the sound and it will be heard by everyone around.
