### ISSUE TITLE
AudioPlayer mod not playing sound from custom discs through default output device

### ISSUE THREAD

**Issue by ironik42** [henkelmax/audio-player#75]
### Bug description

I create a custom music disc and it plays, but not through my default audio device which is my PC speakers. Instead, it will only play through my headset. I have double and triple checked the default audio setting, but it will still only play through my headset.

### Minecraft version

1.20.4

### Simple Voice Chat version

1.20.4-2.5.9

### Mod version

1.20.4-1.8.9

### Mod loader and version

Fabric Loader 0.15.7

### Steps to reproduce

1. start Fabric Minecraft server.(simple voice chat mod is installed)
2. log in to server(simple voice chat is installed with Fabric mod loader)
3. create custom music disc
4. put custom music disc in jukebox
5. sound is output to the wrong audio device

### Expected behavior

I expect the audio from the custom disc to be output to whatever I set my default audio device to be, in this case, my PC speakers.

### Log files

https://gist.github.com/ironik42/f9a0ce0d9537b4d7f3d11541ff1b24d4

**Comment by henkelmax** [comment]
Thats not an issue with the audioplayer mod. The client side is purely voice chat. Please read the voice chat wiki and if you still need help, visit the discord server.
