### ISSUE TITLE
Incompatibility with Eureka! and Sophisticated Backpacks Fabric

### ISSUE THREAD

**Issue by S-moreo** [henkelmax/audio-player#78]
### Bug description

- No audio on Eureka ships
- Vanilla disc audio when using Jukebox upgrade with Sophisticated Backpacks, i.e. Cat will still play Cat and not the custom audio

### Minecraft version

1.20.1

### Simple Voice Chat version

1.20.1-2.5.13

### Mod version

1.20.1-1.8.9

### Mod loader and version

Fabric Loader 0.15.10

### Steps to reproduce

Eureka:
- Write mp3 to custom disk using filebin
- Place jukebox on ship
- Insert disc
- No audio but noteblock particle effects still display

Sophisticated Backpacks:
- Write mp3 to custom disk using filebin
- Insert disc into Jukebox upgrade
- Press play
- Vanilla music plays

### Log files

https://gist.github.com/S-moreo/cf497e5b118d30547d9aa5c9e354628e

**Comment by S-moreo** [comment]
Above log is from the client, server log can be found here:
https://gist.github.com/S-moreo/c470c572e9baa74ad8b0314211e11c12

**Comment by henkelmax** [comment]
This mod only works with vanilla jukeboxes. There are no plans on adding compatibility with other mods that play music discs. This mod is meant to enhance the vanilla gameplay experience.

**Comment by luigistyle** [comment]
What about the issue with Eureka? I assume it happens due to the way VS2 (the parent mod) handles ships, but since Simple Voice Chat works on said ships I assume there should be a way to make Audioplayer compatible as well
