### ISSUE TITLE
1.20.5 version playing goat horn sound with the custom sound

### ISSUE THREAD

**Issue by supernova-relic** [henkelmax/audio-player#79]
### Bug description

Hi, when playing a goat horn with a custom sound assigned, it will play the original horn sound at the same time as the custom sound

### Minecraft version

1.20.5

### Simple Voice Chat version

1.20.5-2.5.12

### Mod version

1.20.5 1.9.1

### Mod loader and version

fabric loader 0.15.10

### Steps to reproduce

create goat horn with custom sound using the upload method
play horn, custom sound and horn sound will both play 

### Expected behavior

just the custom sound

### Log files

hh

### Screenshots

ieiew

**Comment by supernova-relic** [comment]
![modlist](https://github.com/henkelmax/audio-player/assets/137984698/9e7189cc-ab55-4d1e-ad40-7c0bc37e3224)

**Comment by henkelmax** [comment]
This has already been fixed in 1.20.6.
1.20.5 is not supported anymore. Consider switching to 1.20.6.
