### ISSUE TITLE
Fabric 1.18.2 - No audio when connected via server

### ISSUE THREAD

**Issue by dirtyfargo** [henkelmax/audio-player#8]
**Bug description**
In Singleplayer, custom audio plays in jukebox and works great.

When connected via Server, the same .wav file has no audio when played in Jukebox.

I have tried multiple .wav files from different sources as well.

**Steps to reproduce the issue**
1. Connect to world via server.
2. Upload/download/apply song to music disc via commands
3. Play disc in Jukebox

**Expected behavior**
Audible audio

**Log files**
https://gist.github.com/dirtyfargo/20f2358e2c863ee798eaed53f67ebe03

**Versions**
- Minecraft version 1.18.2
- Fabric loader version 0.14.8
- Mod version 1.0.3
- Voice Chat Version 2.2.45

**Other mods**

I use a large modpack, as you can probably see from my log, but I have tested and it occurs with only:
Audioplayer
Voicechat
Fabric API

**Comment by henkelmax** [comment]
Your voice chat is not connected. This is not a bug of the audio player mod.
