### ISSUE TITLE
Audio files do not download from filebin

### ISSUE THREAD

**Issue by CrashTestJava** [henkelmax/audio-player#80]
### Bug description

When attempting to download an `.mp3` or `.wav` file from filebin using the `/audioplayer upload` command, instead of downloading, the game outputs an error; `Failed to download sound: Stream of unsupported format`. I tested this on some random versions of the mod, and I still got the same error. I have also tested this on a server and it has outputted the same thing. When I checked the game and server logs, it had no information other than: `[12:08:39] [Thread-93/WARN]: CrashTestJava failed to download a sound: Stream of unsupported format` (client) `07.06 17:12:30 [Server] Thread-3187/WARN CrashTestJava failed to download a sound: Stream of unsupported format` (server). When I had previously used this mod on the same game version only a few weeks ago, it worked perfectly fine. #

### Minecraft version

1.20.1

### Simple Voice Chat version

1.20.1 (2.5.15)

### Mod version

any

### Mod loader and version

0.15.10

### Steps to reproduce

**1.** Join a world or server
**2.** Type `/audioplayer upload` 
**3.** Upload your audio file as a `.mp3` or `.wav`
**4.** After your audio file has uploaded, download the file

### Expected behavior

The file downloads.

### Log files

x

### Screenshots

![image](https://github.com/henkelmax/audio-player/assets/135138016/7a95eedd-111a-4417-8099-0b68d51f5e54)
![image](https://github.com/henkelmax/audio-player/assets/135138016/4a734c6b-e2c8-4a64-a431-69f9bb6093fe)

**Comment by henkelmax** [comment]
Please send me your audio file.

**Comment by CrashTestJava** [comment]
Sorry, version 1.10.1.
Here is the audio file: https://crashtestjava.github.io/INTOTHECITY.wav
Might I note that I manage a small modded smp with some friends, and they have the same issue on said smp, so I don't think it's the audio file.

**Comment by CrashTestJava** [comment]
Thank you!
