### ISSUE TITLE
Both wav and mp3 claim to be unsupported in-game

### ISSUE THREAD

**Issue by Newtboy** [henkelmax/audio-player#81]
### Bug description

Whenever I try to upload a sound (either in .mp3 or .wav), it states either "Failed to download sound: Invalid file format" or "Failed to download sound: Unsupported file format". No mentions of this issue anywhere else online that I can find.

### Minecraft version

1.19.2

### Simple Voice Chat version

1.19.2-2.5.15

### Mod version

1.19.2-1.8.9

### Mod loader and version

Fabric Loader 0.15.11

### Steps to reproduce

add file to server
attempt to register in-game through the /audioplayer serverfile "nameoffile.extension"
returns: "Failed to download sound: Unsupported file format"

add file to dropbox
attempt the /audioplayer URL "valid dropbox URL with end as 1 instead of 0" command
returns: "Failed to download sound: Invalid file format"

### Expected behavior

run the command(s)
expected result
put on goat horn

### Log files

https://gist.github.com/Newtboy/80bda938993674aa20955985b8730d2d

### Screenshots

<img width="550" alt="Screenshot 2024-06-07 at 1 57 27 PM" src="https://github.com/henkelmax/audio-player/assets/85029246/1d2ee538-5f7e-4113-9dc5-f78aafd7f3d5">

**Comment by henkelmax** [comment]
Can you send me the audio file you uploaded?
Also please update the mod to the latest version.

**Comment by Newtboy** [comment]
https://www.dropbox.com/scl/fo/fw4cvp1as7h5r1t11tzvt/AFJwKSPcAj445WGlDYb7v8Q?rlkey=65qxs0hf89llwwbu9lyh0iopr&st=93pmw0lt&dl=0

**Comment by henkelmax** [comment]
Thats not the latest version of the mod.

**Comment by Newtboy** [comment]
According to curseforge, it is.
![Screenshot 2024-06-08 at 10 15 15 AM](https://github.com/henkelmax/audio-player/assets/85029246/ae8b27b0-7bf9-45bf-917d-b0952c4eb9a6)

**Comment by Newtboy** [comment]
I still don't see a new version for 1.19.2, are newer versions compatible with 1.19.2?
The server I'm on won't update past .2, as the owner said "it took too long to set this up and I don't wanna bother changing these mods again" so I can't do anything about that.

**Comment by henkelmax** [comment]
CurseForge is really bad with synchronizing files to the launcher and alpha versions in general. I'd highly recommend using modrinth.

**Comment by Newtboy** [comment]
Thank you, they appear there!
