### ISSUE TITLE
AudioPlayer does not work with Valkryien Skies

### ISSUE THREAD

**Issue by glypy** [henkelmax/audio-player#84]
### Bug description

When using a jukebox on an assembled ship from Valkryien Skies, the Jukebox does not emit a custom sound, just plays the particles.

### Minecraft version

1.20.1

### Simple Voice Chat version

1.20.1-2.5.18

### Mod version

1.10.2

### Mod loader and version

Fabric Loader 0.92.2+1.20.1

### Steps to reproduce

1. Download Valkryien Skies + Eureka!
2. Download AudioPlayer
3. Start game, create new world, upload custom audio file onto music disc.
4. Place down jukebox on assembled ship (use the helm)
5. Insert music disc

### Expected behavior

Custom music to play.

### Log files

No errors in logs.

**Comment by henkelmax** [comment]
The mod only works with vanilla jukeboxes.
