### ISSUE TITLE
Jukebox not playing audio after serverfile application onto disc

### ISSUE THREAD

**Issue by haselmere** [henkelmax/audio-player#85]
### Bug description

jukebox not playing custom audio file that I applied onto a disc through the /audioplayer serverfile (selected file) command. This was attempted on a personal minecraft survival server, hosted through godlike.

### Minecraft version

1.20.4

### Simple Voice Chat version

1.20.4

### Mod version

1.20.4

### Mod loader and version

Fabric Loader 1.20.4

### Steps to reproduce

1. join a survival minecraft server that you’re able to manage the files of, as well as having the mod.
2. Insert custom mp3 file into audioplayer uploads folder on the server.
3. Apply audio file to any disc in server through command.
4. Place disc in jukebox.
9:53 PM

### Expected behavior

For the audio to play as it normally would on singleplayer

### Log files

I don't know how to locate or access the log files for the server

**Comment by henkelmax** [comment]
I can't help you without logs.
