### ISSUE TITLE
Filebin downloads not working on 1.20.1

### ISSUE THREAD

**Issue by CocoaTheBoo** [henkelmax/audio-player#91]
### Minecraft version

1.20.1

### Simple Voice Chat version

1.20.1-2.4.32

### Mod version

1.8.9

### Mod loader and version

Fabric Loader 0.15.11

### Steps to reproduce

Log onto a server with the mod installed.
Type /audioplayer upload
Click on the first link
Upload file
Click the second link

### Expected behavior

The audio downloads ready to go

### Log files

https://gist.github.com/CocoaTheBoo/aba8e56add61628893842418180901fb

### Screenshots

![image](https://github.com/user-attachments/assets/1f2126e4-4c02-4180-85bf-f4a6447398d9)

**Comment by henkelmax** [comment]
You are using an outdated version. This has already been fixed.
