### ISSUE TITLE
Songs fail to download

### ISSUE THREAD

**Issue by DiamondJedi** [henkelmax/audio-player#93]
### Bug description

When I try and download a song, using filebin,
![Screenshot_37](https://github.com/user-attachments/assets/4e182ccc-f261-48f0-8146-4af6e0b864f1)
When I try and download a song using server file or url
![Screenshot_39](https://github.com/user-attachments/assets/9eb4821a-36e3-4c31-a35c-c411b4246b7b)

### Minecraft version

1.20.1

### Simple Voice Chat version

1.20.1-2.5.24

### Mod version

1.20.1-1.11.0

### Mod loader and version

Fabric Loader 0.16.5

### Steps to reproduce

1."/audioplayer filebin" in chat
2. click link, upload song and click "here"

### Expected behavior

1."/audioplayer filebin" in chat
2. click link, upload song and click "here"
3. successfully downloaded, paste onto item

### Log files

https://gist.github.com/DiamondJedi/3c27be296a88c16b65def27efb8b5dd4

### Screenshots

![Screenshot_36](https://github.com/user-attachments/assets/d4b35d6e-09dd-433b-bdb9-2c6f77a85f57)
![Screenshot_39](https://github.com/user-attachments/assets/af7165e2-e6e8-4ff5-80ee-1d7fa8325f90)

**Comment by henkelmax** [comment]
Thats not a bug. The file just has an unsupported format. Please visit the simple voice chat discord if you need help with uploading audio.
