### ISSUE TITLE
Server crash on startup when the mod "Player Roles" is present

### ISSUE THREAD

**Issue by NilsLehrfeld** [henkelmax/audio-player#94]
### Bug description

While starting the server with the combination of "Player Roles" + "audioplayer" or your other mod "Enhanced Groups", the server crashes.

I was unsure where to post this Issue, so just to be save I will also share the crash logs with the author of the Player Roles mod.

### Minecraft version

1.121.1

### Simple Voice Chat version

1.21.1-2.5.25

### Mod version

1.21.1-1.13.0

### Mod loader and version

Fabric Loader 0.16.7

### Steps to reproduce

1. Install Fabric Server 1.21.1
2. Install Simple Voicechat + AudioPlayer or Enhanced Groups
3. Install Player Roles + Fabric API
4. Start Server

### Log files

https://gist.github.com/NilsLehrfeld/dfef0c3f497131d0a4cd6daa08be041e

**Comment by henkelmax** [comment]
This is most likely caused by the player roles mod shipping with an outdated version of fabric-permissions-api

**Comment by henkelmax** [comment]
You should report the issue to the player roles mod, as the crash seems to happen with different mods but always with player roles. It seems to happen in their mixins.
