### ISSUE TITLE
1.21.3 crash when player joins world

### ISSUE THREAD

**Issue by Jeefongithub** [henkelmax/audio-player#95]
### Bug description

When player joins world with Audioplayer 1.21.3-1.13.0 mod installed the server crashes. Once I remove the audioplayer mod the player is able to join without issue

### Minecraft version

1.21.3

### Simple Voice Chat version

1.21.3-2.5.25

### Mod version

1.21.3-1.13.0

### Mod loader and version

Fabric Loader 0.16.7

### Steps to reproduce

1. Upgrade existing 1.20 server to 1.21.3
2. Upgrade mods and datapacks to lastest 1.21.3 version
3. Start server
4. When player joins server crashes

### Expected behavior

Player is able to join server

### Log files

https://gist.github.com/Jeefongithub/8802ba732802db1f6871272ef24eea94

**Comment by henkelmax** [comment]
You are using a mod that ships with an outdated/broken version of fabric-permissions-api. This is not an issue with this mod.
