### ISSUE TITLE
erroring when filename contains cyrillic

### ISSUE THREAD

**Issue by svxer** [henkelmax/audio-player#97]
### Bug description

when uploading from file in the server folder, it doesnt want to accept cyrillic, saying that filename should contain only letters, numbers and some symbols

### Minecraft version

1.21.4

### Simple Voice Chat version

fabric-1.21.4-2.5.27

### Mod version

fabric-1.21.4-1.13.1

### Mod loader and version

fabric loader 0.16.9-1.21.4

### Steps to reproduce

1. put a file with cyrillic symbols in required folder
2. try to run the command
3. says that the name is invalid

### Expected behavior

uploading files with cyrillic symbols

### Log files

-

**Comment by henkelmax** [comment]
This is completely intentional. The only allowed characters are `A-Z`, `a-z`, `_`, `-` and ` `.
