### ISSUE TITLE
Conflict with FabricTailor

### ISSUE THREAD

**Issue by Pixeloran** [henkelmax/audio-player#98]
### Bug description

Server crashes when using both fabrictailor and audioplayer 

I was using both mods since 1.20 and there was no problem, but in 1.21.4 is. I even reported it to FabricTailor's creator and he said I should write there. He said that FT bundles fabric permissions api and that is the issue. He also provided me Specific line of the log:

`de.maxhenkel.audioplayer.AudioPlayerPermissionManager$Permission.checkFabricPermission`

### Minecraft version

1.21.4

### Simple Voice Chat version

1.21.4-2.5.26

### Mod version

1.21.4-1.13.1

### Mod loader and version

Fabric Loader 0.16.9

### Steps to reproduce

1. Make server
2. Add Simple Voice Chat, Audioplayer, FabricTailor and fabric api to it
3. Start the server
4. Try to join

### Log files

https://mclo.gs/QEoXosD

**Comment by henkelmax** [comment]
This is not an issue with the audioplayer mod. This is caused by another mod shipping with an outdated version of the fabric permissions api.

**Comment by Pixeloran** [comment]
So how to fix it?

**Comment by henkelmax** [comment]
Report the issue to the mod in question.

**Comment by henkelmax** [comment]
https://github.com/samolego/FabricTailor/blob/b161b62cab190de9ceb4fc2b134be320f0071447/build.gradle#L43

Thats the issue. 
![image](https://github.com/user-attachments/assets/ee6d9df5-47d7-40b1-8847-353f40d95df0)
https://github.com/lucko/fabric-permissions-api/releases

They are using an outdated version. Report it to Fabric Tailor.
